-
  name: Apple iPhone 7 Plus 256GB Red Special Edition
  image: demo/products/apple-iphone7-special.jpg
  producer: Apple
  price: $499

-
  name: Apple MacBook Pro i7 3,1GHz/16/512/Radeon 560 Space Gray
  image: demo/products/apple-macbook-pro.jpg
  producer: Apple
  price: $1499

-
  name: Apple iPhone 7 32GB Jet Black
  image: demo/products/apple-iphone7.jpg
  producer: Apple
  price: $499

-
  name: GoPro HERO6 Black
  image: demo/products/gopro-hero.jpg
  producer: GoPro
  price: $599

-
  name: MSI GV62 i5-7300HQ/8GB/1TB/Win10X GTX1050
  image: demo/products/msi.jpg
  producer: MSI
  price: $1599

-
  name: Xiaomi Mi A1 64GB Black
  image: demo/products/xiaomi-mi.jpg
  producer: Xiaomi
  price: $269

-
  name: Huawei Mate 10 Pro Dual SIM Gray
  image: demo/products/huawei-mate.jpg
  producer: Huawei
  price: $999

-
  name: Sony KD-49XE7005
  image: demo/products/sony-kd.jpg
  producer: Sony
  price: $799

-
  name: Samsung Galaxy A5 A520F 2017 LTE Black Sky
  image: demo/products/samsung-galaxy.jpg
  producer: Samsung
  price: $399